"""Sb model changes

Revision ID: 87858c8a4a69
Revises: 456206d983e6
Create Date: 2026-03-05 09:26:20.594742+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87858c8a4a69'
down_revision: Union[str, Sequence[str], None] = '456206d983e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_cache', sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'schema_cache', ['db_connection_id'])
    op.drop_column('schema_cache', 'created_at')
    op.drop_column('schema_cache', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_cache', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('schema_cache', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schema_cache', type_='unique')
    op.drop_column('schema_cache', 'last_synced')
    # ### end Alembic commands ###