"""Db columns modified

Revision ID: 588afd5fc734
Revises: c88de75730cd
Create Date: 2026-03-07 06:08:47.391874+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588afd5fc734'
down_revision: Union[str, Sequence[str], None] = 'c88de75730cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_connection', 'host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('db_connection', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('db_connection', 'db_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('db_connection', 'encrypted_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_connection', 'encrypted_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('db_connection', 'db_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('db_connection', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('db_connection', 'host',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###