"""fix role column length

Revision ID: e51f34f9e508
Revises: b1cc76534806
Create Date: 2026-03-11 05:38:44.041026+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51f34f9e508'
down_revision: Union[str, Sequence[str], None] = 'b1cc76534806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('user', 'assistant', name='chatrole', native_enum=False, length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'role',
               existing_type=sa.Enum('user', 'assistant', name='chatrole', native_enum=False, length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###