"""Schema module updated

Revision ID: c88de75730cd
Revises: 87858c8a4a69
Create Date: 2026-03-05 09:37:48.714164+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c88de75730cd'
down_revision: Union[str, Sequence[str], None] = '87858c8a4a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_cache', sa.Column('schema_hash', sa.String(), nullable=False))
    op.add_column('schema_cache', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('schema_cache', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schema_cache', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('schema_cache', 'last_synced')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_cache', sa.Column('last_synced', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('schema_cache', 'updated_at')
    op.drop_column('schema_cache', 'created_at')
    op.drop_column('schema_cache', 'version')
    op.drop_column('schema_cache', 'schema_hash')
    # ### end Alembic commands ###