"""Chat columns modified

Revision ID: b1cc76534806
Revises: 588afd5fc734
Create Date: 2026-03-08 09:04:24.248749+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1cc76534806'
down_revision: Union[str, Sequence[str], None] = '588afd5fc734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('query_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('chat_session', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_session', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chat_message', 'query_result')
    # ### end Alembic commands ###